spring:
  application:
    name: rides-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5435/rides}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  liquibase:
    change-log: db/changelog/main-changelog.xml

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
        alphanumeric-ids:
          enabled: true

resilience4j:
  retry:
    configs:
      default:
        ignore-exceptions:
          - com.modsen.ridesservice.client.CustomFeignClientException
  circuitbreaker:
    configs:
      default:
        ignore-exceptions:
          - com.modsen.ridesservice.client.CustomFeignClientException
        register-health-indicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 51
        eventConsumerBufferSize: 10
  timelimiter:
    configs:
      default:
        timeout-duration:
          seconds: 4

management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: rides-service

server:
  port: 8087

eureka:
  client:
    service-url:
      defaultZone:
        ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
