spring:
  application:
    name: rides-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5435/rides}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  liquibase:
    change-log: db/changelog/main-changelog.xml

server:
  port: 8087

eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:8761/eureka/
