spring:
  application:
    name: rides-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URL:http://localhost:8090/realms/cab-aggregator-app}

  cache:
    type: redis
    redis:
      time-to-live: ${REDIS_CACHE_TTL:60m}
      cache-null-values: false
  data:
    redis:
      host: ${REDIS_CACHE_URL:localhost}
      port: ${REDIS_CACHE_PORT:6380}

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5435/rides}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  liquibase:
    change-log: db/changelog/main-changelog.xml

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
        alphanumeric-ids:
          enabled: true

resilience4j:
  retry:
    configs:
      default:
        ignore-exceptions:
          - com.modsen.ridesservice.client.CustomFeignClientException
  circuitbreaker:
    configs:
      default:
        ignore-exceptions:
          - com.modsen.ridesservice.client.CustomFeignClientException
        register-health-indicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 51
        eventConsumerBufferSize: 10
  timelimiter:
    configs:
      default:
        timeout-duration:
          seconds: 4

management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  zipkin:
    tracing:
      endpoint: ${TEMPO_ZIPKIN_URL:http://localhost:9411/api/v2/spans}
  tracing:
    sampling:
      probability: 1.0
  metrics:
    tags:
      application: rides-service


server:
  port: 8087

eureka:
  instance:
    metadataMap:
      "prometheus.scrape": "true"
      "prometheus.path": "/actuator/prometheus"
      "prometheus.port": "8087"
  client:
    service-url:
      defaultZone:
        ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
