scrape_configs:
  - job_name: "discovery-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8761", "discovery-service:8761"]
  - job_name: "gateway-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "host.docker.internal:8080", "discovery-service:8080" ]
  - job_name: "passenger-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "host.docker.internal:8086", "passenger-service:8086" ]
  - job_name: "driver-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "host.docker.internal:8085", "driver-service:8085" ]
  - job_name: "rides-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "host.docker.internal:8087", "rides-service:8087" ]
  - job_name: "rating-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ "host.docker.internal:8088", "discovery-service:8088" ]