spring:
  application:
    name: rating-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5436/ratings}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  liquibase:
    change-log: db/changelog/main-changelog.xml

  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:29092, localhost:29093, localhost:29094}
      client-id: "average-rating-producer"

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: rating-service

server:
  port: 8088

eureka:
  client:
    service-url:
      defaultZone:
        ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
