spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: driver-service
          uri: lb://driver-service
          predicates:
            - Path=${defaultApiPath}/cars/**, ${defaultApiPath}/drivers/**

        - id: passenger-service
          uri: lb://passenger-service
          predicates:
            - Path=${defaultApiPath}/passengers/**

        - id: rating-service
          uri: lb://rating-service
          predicates:
            - Path=${defaultApiPath}/passengers-ratings/**, ${defaultApiPath}/drivers-ratings/**

        - id: rides-service
          uri:  lb://rides-service
          predicates:
            - Path=${defaultApiPath}/rides/**
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}


defaultApiPath: /api/v1