spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: driver-service
          uri: lb://driver-service
          predicates:
            - Path=${defaultApiPath}/cars/**, ${defaultApiPath}/drivers/**, /driver-service/v3/api-docs
          filters:
            - RewritePath=/driver-service/(?<segment>.*), /${segment}

        - id: passenger-service
          uri: lb://passenger-service
          predicates:
            - Path=${defaultApiPath}/passengers/**, /passenger-service/v3/api-docs
          filters:
            - RewritePath=/passenger-service/(?<segment>.*), /${segment}

        - id: rating-service
          uri: lb://rating-service
          predicates:
            - Path=${defaultApiPath}/passengers-ratings/**, ${defaultApiPath}/drivers-ratings/**, /rating-service/v3/api-docs
          filters:
            - RewritePath=/rating-service/(?<segment>.*), /${segment}

        - id: rides-service
          uri: lb://rides-service
          predicates:
            - Path=${defaultApiPath}/rides/**, /rides-service/v3/api-docs
          filters:
            - RewritePath=/rides-service/(?<segment>.*), /${segment}

        - id: registration-service
          uri: lb://registration-service
          predicates:
            - Path=${defaultApiPath}/cab-aggregator/**, /registration-service/v3/api-docs
          filters:
            - RewritePath=/registration-service/(?<segment>.*), /${segment}

server:
  port: 8080
eureka:
  instance:
    metadataMap:
      "prometheus.scrape": "true"
      "prometheus.path": "/actuator/prometheus"
      "prometheus.port": "8080"
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  zipkin:
    tracing:
      endpoint: ${TEMPO_ZIPKIN_URL:http://localhost:9411/api/v2/spans}
  tracing:
    sampling:
      probability: 1.0
  metrics:
    tags:
      application: gateway-service

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    urls:
      - url: /v3/api-docs
        name: API cab-aggregator-app
      - url: /driver-service/v3/api-docs
        name: Driver Service
      - url: /passenger-service/v3/api-docs
        name: Passenger Service
      - url: /rating-service/v3/api-docs
        name: Rating Service
      - url: /rides-service/v3/api-docs
        name: Rides Service
      - url: /registration-service/v3/api-docs
        name: Registration Service


defaultApiPath: /api/v1