version: '3.8'

services:
  passengers-db-e2e:
    image: postgres:latest
    container_name: passengers_db_e2e
    environment:
      POSTGRES_DB: passengers
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  drivers-db-e2e:
    image: postgres:latest
    container_name: drivers_db_e2e
    environment:
      POSTGRES_DB: drivers
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"

  rides-db-e2e:
    image: postgres:latest
    container_name: rides_db_e2e
    environment:
      POSTGRES_DB: rides
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"

  rating-db-e2e:
    image: postgres:latest
    container_name: rating_db_e2e
    environment:
      POSTGRES_DB: ratings
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"

  zookeeper-e2e:
    image: bitnami/zookeeper:3.5
    container_name: zookeeper_e2e
    ports:
      - "2181"
    networks:
      - kafkanet-e2e
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka-0-e2e:
    image: bitnami/kafka:2.8.1
    container_name: kafka_0_e2e
    expose:
      - 9092
    ports:
      - "29092:29092"
    networks:
      - kafkanet-e2e
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper_e2e:2181
      - KAFKA_CFG_BROKER_ID=0
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka-0-e2e:9092,EXTERNAL://localhost:29092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
    depends_on:
      - zookeeper-e2e

  kafka-1-e2e:
    image: bitnami/kafka:2.8.1
    container_name: kafka_1_e2e
    expose:
      - 9092
    ports:
      - "29093:29093"
    networks:
      - kafkanet-e2e
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper_e2e:2181
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:29093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka-1-e2e:9092,EXTERNAL://localhost:29093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
    depends_on:
      - zookeeper-e2e

  kafka-2-e2e:
    image: bitnami/kafka:2.8.1
    container_name: kafka_2_e2e
    expose:
      - 9092
    ports:
      - "29094:29094"
    networks:
      - kafkanet-e2e
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper_e2e:2181
      - KAFKA_CFG_BROKER_ID=2
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:29094
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka-2-e2e:9092,EXTERNAL://localhost:29094
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
    depends_on:
      - zookeeper-e2e

  kafka-ui-e2e:
    image: provectuslabs/kafka-ui:master
    container_name: kafka_ui_e2e
    ports:
      - "8079:8080"
    networks:
      - kafkanet-e2e
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-0:9092,kafka-1:9092,kafka-2:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper_e2e:2181

networks:
  kafkanet-e2e:
    name: kafka_network_e2e