spring:
  application:
    name: discovery-service
eureka:
  client:
    register-with-eureka: false #defines is discovery-service registered as client
    fetch-registry: false #accept or not information about registered services
server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: discovery-service