spring:
  application:
    name: driver-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5434/drivers}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  liquibase:
    change-log: db/changelog/main-changelog.xml

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone:
        ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
